### ISSUE TITLE
error with Render the tutorial report

### ISSUE THREAD

**Issue by Jordthomas93** [nanoporetech/ont_tutorial_cdna_deseq2#2]
Cannot complete the stage: Render the tutorial report using the command below
    R --slave -e 'rmarkdown::render("Nanopore_cDNA_Tutorial.Rmd", "html_document")'

Returning this error: 
running: bash  -c 'conda list "samtools|minimap2|snakemake|rstudio"'
Quitting from lines 522-523 (Nanopore_cDNA_Tutorial.Rmd)
Error in system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) :
  error in running command
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

Execution halted

Any ideas whats going on?

Running ubuntu for windows (WSL)

Thanks!

**Comment by sagrudd** [comment]
Thanks for the message! I haven't tested this tutorial with WSL.

The source of the error in the Rmarkdown script is a best-practices step where the versions of the conda installed packages are displayed and added to the report.  It seems that the R code is not able to run the "conda list" command - this expects to be called within a bash shell.

What happens when you type 

bash -c 'conda list "samtools|minimap2|snakemake|rstudio"'

in your shell?

Could you also give me the output from typing "echo $0"?

Apologies for the inconvenience here; I do not have access to WSL and have not tested with this configuration - we'll get this tutorial working for you soon!

**Comment by Jordthomas93** [comment]
Hiya,

Thanks for the response!

Here is what i got for both
(cDNA_DESeq2) jordan@watt27:~/cDNA_DESeq2$ bash -c 'conda list "samtools|minimap2|snakemake|rstudio"'
bash: conda: command not found

(cDNA_DESeq2) jordan@watt27:~/cDNA_DESeq2$ echo $0
/bin/bash

**Comment by Jordthomas93** [comment]
Also, i am quite new to this so i could be doing things wrong haha!

**Comment by sagrudd** [comment]
bash is thus installed and working - your conda installation has not been completed. Can you run the 

source activate cDNA_DESeq2 

command again. This loads your conda environment and needs to be run each time you open a new bash console. If you then try

bash -c 'conda list "samtools|minimap2|snakemake|rstudio"'

then you should get some version information for the required packages.

If this works then you should be set for the 

R --slave -e 'rmarkdown::render("Nanopore_cDNA_Tutorial.Rmd", "html_document")'

Good luck!

**Comment by Jordthomas93** [comment]
Yep that worked!

Thanks!

**Comment by sagrudd** [comment]
Fabulous - thanks for the confirmation of progress! Watch this space; there will be some new tutorials released over the next few days
